defaults:
  - model_checkpoint.yaml
  - early_stopping.yaml
  - model_summary.yaml
  - rich_progress_bar.yaml
  - _self_

model_checkpoint:
  dirpath: checkpoints/
  filename: ${model.net._target_}_${model.net.subspace_size}_${seed}
  monitor: "val/paired_pred_loss"
  mode: "min"
  auto_insert_metric_name: False

early_stopping:
  monitor: "val/paired_pred_loss"
  patience: 20
  mode: "min"

model_summary:
  max_depth: -1
