defaults:
  - model_checkpoint.yaml
  - early_stopping.yaml
  - model_summary.yaml
  - rich_progress_bar.yaml
  - _self_

model_checkpoint:
  dirpath: checkpoints/${model.net._target_}_${model.net.subspace_size}_${seed}
  filename: "epoch_{epoch:03d}"
  monitor: "val/paired_pred_loss"
  mode: "min"
  save_last: True
  auto_insert_metric_name: False

early_stopping:
  monitor: "val/paired_pred_loss"
  patience: 20
  mode: "max"

model_summary:
  max_depth: -1
